server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    
    # Archivo por defecto si entras a la raíz
    index frontend_portal.html;

    # 1. Atajo para el Dashboard del Gobierno
    location = /issuer {
        try_files /issuer_dashboard.html =404;
    }

    # 2. Atajo para el Dashboard de la Empresa/Banco
    location = /verifier {
        try_files /verifier_dashboard.html =404;
    }

    # 3. Regla general (quita los .html si alguien los escribe)
    location / {
        try_files $uri $uri.html /frontend_portal.html;
    }

    # Caché para variables dinámicas (no cachear)
    location = /frontend.variables.js {
        add_header Cache-Control "no-store";
    }

    # Caché para estáticos (imágenes, css, js)
    location ~* \.(?:css|js|png|jpg|jpeg|gif|svg|ico|woff2?)$ {
        add_header Cache-Control "public, max-age=604800";
        expires 7d;
        try_files $uri =404;
    }
}