server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index frontend_portal.html;

    location / {
        # Si no encuentra la ruta exacta, busca con .html, 
        # y si tampoco, ¡carga el portal a la fuerza!
        try_files $uri $uri.html /frontend_portal.html;
    }

    location = /frontend.variables.js {
        add_header Cache-Control "no-store";
    }

    location ~* \.(?:css|js|png|jpg|jpeg|gif|svg|ico|woff2?)$ {
        add_header Cache-Control "public, max-age=604800";
        expires 7d;
        try_files $uri =404;
    }
}
